### ISSUE TITLE
Module '"tapable"' has no exported member 'Tapable'. 

### ISSUE THREAD

**Issue by Fxztam** [chatbotgang/web-components-demo#1]
Try to  `$ yarn workspace @web-components-demo/components build`:

[ ERROR ]  TypeScript: ../../node_modules/@types/webpack/index.d.ts:32:3
                 Module '"tapable"' has no exported member 'Tapable'.

**Comment by Joseph7451797** [comment]
Can be fixed by [this way](https://github.com/webpack/webpack/issues/12185#issuecomment-765386938).
